project:
  type: website
  output-dir: docs
website:
  title: "Rocky River Bowling Tour"
  description: Website for the Rocky River Bowling Tour
  site-url: https://rrbtour.org/
  favicon: www/favicon.webp
  open-graph: true
  back-to-top-navigation: true
  page-footer:
    center: "Copyright &#169; 2024-2025 Rocky River Bowling Tour"
  navbar:
    pinned: true
    search: true
    background: "#762F3E"
    foreground: "#FFFFFF"
    left:
      - index.qmd
      - text: "Members"
        href: members/index.qmd
      - text: "Events"
        href: events/index.qmd
      - text: "Locations"
        href: locations/index.qmd
format:
  html:
    smooth-scroll: true
    theme: [flatly, www/custom.scss]
    css: www/styles.css
